# fly.toml - Telegram Weather Bot

app = "weather-bot"  # Replace with your Fly app name if different
primary_region = "iad"  # Change to nearest region (e.g., fra, sea, sfo)

[build]
  # Use local Dockerfile
  dockerfile = "Dockerfile"

[env]
  # Environment variables are optional here if using secrets
  # TELEGRAM_BOT_TOKEN = "your_token"
  # FIREWORKS_API_KEY = "your_key"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

  # We don't actually serve HTTP, just need an open port for Fly
  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "5s"
    restart_limit = 0